'use client';
import {useEffect,useState} from 'react';
import {Calendar} from '@/components/ui/calendar';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {uk} from 'date-fns/locale';
import {ArrowUpRight,Phone,Sun,Waves,Flame,Check,Copy,ArrowRight} from 'lucide-react';
import {initialResources,defaults,totalPrice,Resource} from '@/lib/catalog';
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function BookingSite(){
 const [resources,setResources]=useState(initialResources),[settings,setSettings]=useState(defaults),[kind,setKind]=useState('gazebo'),[date,setDate]=useState<Date>(new Date()),[selected,setSelected]=useState<Resource|null>(null),[start,setStart]=useState(10),[end,setEnd]=useState(13),[guests,setGuests]=useState(8),[deposit,setDeposit]=useState(500),[name,setName]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[occupied,setOccupied]=useState<{resource:string;start:number;end:number}[]>([]),[receipt,setReceipt]=useState<{id:string;total:number;deposit:number}|null>(null),[copied,setCopied]=useState(false);
 useEffect(()=>{let active=true;setReady(false);setError('');Promise.all([fetch('/api/catalog'),fetch('/api/availability?date='+dateKey(date))]).then(async responses=>{if(responses.some(r=>!r.ok))throw Error();return Promise.all(responses.map(r=>r.json()))}).then(([c,a]:any[])=>{if(active){setResources(c.resources);setSettings(c.settings);setOccupied(a.slots);setReady(true)}}).catch(()=>{if(active)setError('Не вдалося перевірити вільні місця. Оновіть сторінку або зателефонуйте адміністратору.')});return()=>{active=false}},[date]);
 useEffect(()=>{const o=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>o.observe(el));return()=>o.disconnect()},[]);
 const todayKyiv=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Kyiv'}).format(new Date());
 const currentHourKyiv=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Kyiv',hour:'2-digit',hourCycle:'h23'}).format(new Date()));
 const earliest=dateKey(date)===todayKyiv?Math.max(settings.open,currentHourKyiv+1):settings.open;
 const minDuration=selected?.kind==='sauna'?3:1;
 const hours=Array.from({length:Math.max(0,settings.close-earliest)},(_,i)=>earliest+i);
 const overlaps=(from:number,to:number,id=selected?.id)=>occupied.some(s=>s.resource===id&&s.start<to&&s.end>from);
 const invalidTime=start<earliest||end>settings.close||end-start<minDuration||(selected?.kind==='sauna'&&overlaps(start,end));
 const lastDay=new Date();lastDay.setFullYear(lastDay.getFullYear()+1);
 const total=selected?totalPrice(selected,dateKey(date),start,end,guests,settings):0;
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:selected?.id,date:dateKey(date),start,end,guests,deposit,name,phone,expectedTotal:total})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setCopied(false);setReceipt(d);setSelected(null);setOccupied(v=>[...v,{resource:selected!.id,start,end}]);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><header><a href='/' className='brand'>kumanyok<span>відпочинок біля води</span></a><nav><a href='#booking'>Бронювання</a><a href='#water'>На воді</a><a href='#contacts'>Контакти</a></nav><a className='header-phone' href='tel:+380995175555'><Phone size={16}/> +380 99 517 55 55</a></header>
 <main><section className='intro'><div className='intro-copy'><p className='eyebrow'>ВАШ ЧАС ДЛЯ ВІДПОЧИНКУ</p><h1>Ближче до природи.<br/><em>Ближче до своїх.</em></h1><p>Альтанки, тепло бані та відпочинок на воді.<br/>Оберіть свій день у Kumanyok.</p><a className='round-link' href='#booking'>Знайти вільне місце <ArrowUpRight size={23}/></a></div><div className='intro-art'><img src='/images/river-art.png' alt='Художня ілюстрація сонячних відблисків на воді'/><div className='art-caption'><Sun/> Гарний день починається тут</div></div></section>
 <section id='booking' className='booking-section'><div className='section-heading'><div><p className='eyebrow'>01 / ПЛАНУЙТЕ СВІЙ ДЕНЬ</p><h2>Місце для ваших планів</h2></div><p>Дата. Місце. Ваша компанія.</p></div><div className='booking-layout'><aside className='calendar-panel'><div className='segmented'><Button variant={kind==='gazebo'?'default':'ghost'} onClick={()=>setKind('gazebo')}>Альтанки</Button><Button variant={kind==='sauna'?'default':'ghost'} onClick={()=>setKind('sauna')}>Баня</Button></div><Calendar mode='single' required selected={date} onSelect={d=>d&&setDate(d)} locale={uk} disabled={[{before:new Date(todayKyiv+'T00:00:00')},{after:lastDay}]}/><div className='calendar-note'><Sun size={20}/><span>Передоплата від 500 грн<br/><small>або повна сума бронювання</small></span></div><p className='muted'>Переказ на картку. Адміністратор підтвердить отримання оплати.</p></aside><div><div className='results-heading'><h3>{date.toLocaleDateString('uk-UA',{day:'numeric',month:'long'})}</h3><span>{kind==='gazebo'?'Альтанки для вашої компанії':'Час для тепла та відновлення'}</span></div>{error&&<p role='alert' className='notice'>{error}</p>}<div className='resource-grid'>{resources.filter(r=>r.kind===kind).map(r=>{const unavailable=(r.kind==='gazebo'&&occupied.some(s=>s.resource===r.id))||!hours.some(h=>h+(r.kind==='sauna'?3:1)<=settings.close&&(r.kind==='gazebo'||!overlaps(h,h+3,r.id)));return <article className='resource-card' key={r.id}>{r.photo&&<img className='resource-photo' loading='lazy' decoding='async' src={r.photo} alt={r.name}/>}<div className='resource-top'><span className='resource-icon'>{r.kind==='sauna'?<Flame/>:<Sun/>}</span><span className='availability'>{unavailable?'Немає вільного часу':ready?'Оберіть час':'Перевірка доступності…'}</span></div><h3>{r.name}</h3><p>{r.description}</p><div className='resource-bottom'><div><strong>{totalPrice(r,dateKey(date),0,1,8,settings).toLocaleString('uk-UA')} ₴</strong><small> / {r.kind==='sauna'?'година':'день'}</small></div><Button disabled={!ready||unavailable} onClick={()=>{setSelected(r);setReceipt(null);setError('');setDeposit(500);const first=hours.find(h=>h+(r.kind==='sauna'?3:1)<=settings.close&&(r.kind==='gazebo'||!overlaps(h,h+3,r.id)))??earliest;setStart(first);setEnd(Math.min(first+3,settings.close))}} aria-label={'Забронювати '+r.name}><ArrowUpRight/></Button></div></article>})}</div></div></div></section>
 <section id='water' className='water-section reveal'><div><p className='eyebrow'>02 / ДОДАЙТЕ ТРОХИ ПРИГОД</p><h2>Змінити берег<br/><em>на водну гладь.</em></h2><p>Гідроцикл для драйву. Човен для спокійної прогулянки.<br/>Доступність і деталі узгодьте з адміністратором.</p><a className='light-link' href='tel:+380995175555'>Домовитися про прогулянку <ArrowUpRight/></a></div><div className='water-options'><article><img src="/images/jetski.jpg" alt="Гідроцикл Kumanyok — кадр з Instagram"/><h3>Гідроцикл</h3><p>Водні пригоди за попередньою домовленістю.</p></article><article><img src="/images/boat-art.png" alt="Художня ілюстрація човна на воді"/><h3>Лодка</h3><p>Прогулянка на воді у вашому темпі.</p></article></div></section>
 <section className='steps reveal'><div><p className='eyebrow'>03 / УСЕ ПРОСТО</p><h2>До зустрічі<br/>в Kumanyok</h2></div>{[['01','Оберіть день','Знайдіть альтанку або час для бані у календарі.'],['02','Залиште контакти','Вкажіть ім’я, телефон і суму передоплати.'],['03','Підтвердьте оплату','Перекажіть кошти на картку та зв’яжіться з адміністратором.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</section></main>
 <footer id='contacts'><a className='brand' href='/'>kumanyok<span>залишайте час для своїх</span></a><a className='footer-phone' href='tel:+380995175555'>+380 99 517 55 55 <ArrowUpRight/></a><div><a href='https://www.instagram.com/kumanyok_zp/' target='_blank' rel='noreferrer'>Instagram ↗</a><a href='/admin'>Для адміністратора</a></div></footer>
 <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className='booking-dialog'><DialogTitle>{selected?.name} · {date.toLocaleDateString('uk-UA')}</DialogTitle><DialogDescription>Заповніть заявку. Бронювання підтверджується після перевірки переказу.</DialogDescription><form onSubmit={submit} className='booking-form'>{selected?.kind==='sauna'&&<p className='muted'>Зайняті години: {occupied.filter(s=>s.resource==='sauna').map(s=>s.start+':00–'+s.end+':00').join(', ')||'немає бронювань'}</p>}<div className='form-row'><label>Початок<select value={start} onChange={e=>{const next=+e.target.value;setStart(next);setEnd(Math.min(Math.max(next+minDuration,end),settings.close))}} required>{hours.filter(h=>h+minDuration<=settings.close).map(h=><option key={h} value={h} disabled={selected?.kind==='sauna'&&overlaps(h,h+3)}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Завершення<select value={end} onChange={e=>setEnd(+e.target.value)} required>{Array.from({length:Math.max(0,settings.close-start-minDuration+1)},(_,i)=>start+minDuration+i).map(h=><option key={h} value={h} disabled={selected?.kind==='sauna'&&overlaps(start,h)}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Гостей<input type='number' min='1' max='100' value={guests} onChange={e=>setGuests(+e.target.value)} required/></label></div>{!settings.hoursConfirmed&&<p className='muted'>Бажаний час узгоджується з адміністратором.</p>}{selected?.kind==='sauna'&&<p className='muted'>Мінімум 3 години. Понад 8 гостей: +{settings.saunaExtra} грн за гостя{settings.extraHourly?' за годину':' за відвідування'}.</p>}<label>Ваше ім’я<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required autoComplete='name'/></label><label>Телефон<input type='tel' value={phone} onChange={e=>setPhone(e.target.value)} placeholder='+380' required autoComplete='tel'/></label><div className='price-summary'><span>Разом</span><strong>{total.toLocaleString('uk-UA')} грн</strong></div><label>Передоплата, грн<input type='number' min='500' max={total} value={deposit} onChange={e=>setDeposit(+e.target.value)} required/></label><p className='muted'>Надсилаючи заявку, ви погоджуєтесь на використання імені та телефону для організації бронювання.</p>{error&&<p role='alert' className='notice'>{error}</p>}<Button type='submit' disabled={busy||total<500||invalidTime}>{busy?'Зберігаємо…':'Створити бронювання'} <ArrowRight size={18}/></Button></form></DialogContent></Dialog>
 <Dialog open={!!receipt} onOpenChange={o=>!o&&setReceipt(null)}><DialogContent><DialogTitle>Заявку збережено <Check/></DialogTitle><DialogDescription>Очікуємо переказ {receipt?.deposit} грн. Це ще не підтвердження оплати.</DialogDescription><p>Номер бронювання: <strong>{receipt?.id}</strong></p><div className='payment-card'><small>Картка для переказу</small><strong>4149 4991 5674 7394</strong><Button variant='secondary' onClick={async()=>{try{await navigator.clipboard.writeText('4149499156747394');setCopied(true)}catch{setCopied(false)}}}>{copied?<Check/>:<Copy/>}{copied?'Скопійовано':'Копіювати'}</Button></div><p>Після переказу повідомте адміністратору номер бронювання. Питання скасування та повернення узгоджуються з ним.</p><a className='round-link' href='tel:+380995175555'><Phone/> +380 99 517 55 55</a></DialogContent></Dialog></>;
}





